DEBUG 2018-06-13 13:02:27,014: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:02:27,014: 	 Could not find CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3; creating a new one.
DEBUG 2018-06-13 13:02:27,061: 	 Checking credentials
DEBUG 2018-06-13 13:02:27,063: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:02:27,063: 	 Getting proxy life time left
DEBUG 2018-06-13 13:02:28,773: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604507

 error: 
 retcode : 0
DEBUG 2018-06-13 13:02:30,002: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604506

 error: 
 retcode : 0
DEBUG 2018-06-13 13:02:30,002: 	 Proxy valid for 167:55:07 hours
ERROR 2018-06-13 13:02:30,002: 	 CRAB configuration file heppy_crab_config_env.py not found.
ERROR 2018-06-13 13:02:30,002: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file heppy_crab_config_env.py not found.
DEBUG 2018-06-13 13:04:39,802: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:04:39,802: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:04:39,810: 	 Checking credentials
DEBUG 2018-06-13 13:04:39,811: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:04:39,811: 	 Getting proxy life time left
DEBUG 2018-06-13 13:04:40,724: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604375

 error: 
 retcode : 0
DEBUG 2018-06-13 13:04:41,533: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604374

 error: 
 retcode : 0
DEBUG 2018-06-13 13:04:41,533: 	 Proxy valid for 167:52:55 hours
INFO 2018-06-13 13:04:41,534: 	 Will use CRAB configuration file heppy_crab_config_env.py
DEBUG 2018-06-13 13:04:41,534: 	 Loading CRAB configuration file.
ERROR 2018-06-13 13:04:41,548: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: 'heppy_crab_config.py'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-06-13 13:04:41,548: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: 'heppy_crab_config.py'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-06-13 13:05:10,607: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:05:10,607: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:05:10,617: 	 Checking credentials
DEBUG 2018-06-13 13:05:10,618: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:05:10,618: 	 Getting proxy life time left
DEBUG 2018-06-13 13:05:11,628: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604344

 error: 
 retcode : 0
DEBUG 2018-06-13 13:05:12,435: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604343

 error: 
 retcode : 0
DEBUG 2018-06-13 13:05:12,435: 	 Proxy valid for 167:52:24 hours
INFO 2018-06-13 13:05:12,435: 	 Will use CRAB configuration file heppy_crab_config_env.py
DEBUG 2018-06-13 13:05:12,436: 	 Loading CRAB configuration file.
DEBUG 2018-06-13 13:05:12,449: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2018-06-13 13:05:12,450: 	 Cannot find the file heppy_crab_script.sh specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-06-13 13:05:12,450: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Cannot find the file heppy_crab_script.sh specified in the JobType.scriptExe configuration parameter.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-06-13 13:06:49,446: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:06:49,446: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:06:49,457: 	 Checking credentials
DEBUG 2018-06-13 13:06:49,458: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:06:49,458: 	 Getting proxy life time left
DEBUG 2018-06-13 13:06:50,373: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604792

 error: 
 retcode : 0
DEBUG 2018-06-13 13:06:51,181: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604791

 error: 
 retcode : 0
DEBUG 2018-06-13 13:06:51,182: 	 Proxy valid for 167:59:52 hours
INFO 2018-06-13 13:06:51,182: 	 Will use CRAB configuration file heppy_crab_config_env.py
DEBUG 2018-06-13 13:06:51,182: 	 Loading CRAB configuration file.
DEBUG 2018-06-13 13:06:51,184: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2018-06-13 13:06:51,184: 	 Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
ERROR 2018-06-13 13:06:51,184: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
DEBUG 2018-06-13 13:17:54,728: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:17:54,728: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:17:54,737: 	 Checking credentials
DEBUG 2018-06-13 13:17:54,738: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:17:54,739: 	 Getting proxy life time left
DEBUG 2018-06-13 13:17:55,645: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604789

 error: 
 retcode : 0
DEBUG 2018-06-13 13:17:56,450: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604788

 error: 
 retcode : 0
DEBUG 2018-06-13 13:17:56,451: 	 Proxy valid for 167:59:49 hours
INFO 2018-06-13 13:17:56,451: 	 Will use CRAB configuration file heppy_crab_config_env.py
DEBUG 2018-06-13 13:17:56,451: 	 Loading CRAB configuration file.
DEBUG 2018-06-13 13:17:56,453: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2018-06-13 13:17:56,454: 	 Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
ERROR 2018-06-13 13:17:56,454: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
DEBUG 2018-06-13 13:22:55,233: 	 Executing command: 'checkusername'
DEBUG 2018-06-13 13:22:55,233: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:22:55,245: 	 Checking credentials
DEBUG 2018-06-13 13:22:55,246: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:22:55,246: 	 Getting proxy life time left
DEBUG 2018-06-13 13:22:56,156: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604514

 error: 
 retcode : 0
DEBUG 2018-06-13 13:22:56,862: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604514

 error: 
 retcode : 0
DEBUG 2018-06-13 13:22:56,862: 	 Proxy valid for 167:55:14 hours
DEBUG 2018-06-13 13:22:56,975: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /O=GRID-FR/C=FR/O=CNRS/OU=IPNL/CN=Lucas Torterotot

 error: 
 retcode : 0
DEBUG 2018-06-13 13:22:56,976: 	 Checking credentials
DEBUG 2018-06-13 13:22:56,976: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:22:56,976: 	 Getting proxy life time left
DEBUG 2018-06-13 13:22:57,784: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604513

 error: 
 retcode : 0
DEBUG 2018-06-13 13:22:58,592: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604512

 error: 
 retcode : 0
DEBUG 2018-06-13 13:22:58,593: 	 Proxy valid for 167:55:13 hours
DEBUG 2018-06-13 13:22:58,593: 	 Command use: checkusername
DEBUG 2018-06-13 13:22:58,593: 	 Options use: []
DEBUG 2018-06-13 13:22:58,593: 	 Instance is None
DEBUG 2018-06-13 13:22:58,593: 	 Server base url is None
INFO 2018-06-13 13:22:58,593: 	 Retrieving DN from proxy...
INFO 2018-06-13 13:23:00,366: 	 DN is: /O=GRID-FR/C=FR/O=CNRS/OU=IPNL/CN=Lucas Torterotot
INFO 2018-06-13 13:23:00,366: 	 Retrieving username from SiteDB...
ERROR 2018-06-13 13:23:03,618: 	 Error: Failed to retrieve username from SiteDB. Your DN does not seem to be registered in SiteDB.
Details follow:
  Executed command: curl -s --capath /etc/grid-security/certificates --cert /tmp/x509up_u113210 --key /tmp/x509up_u113210 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
    Stdout:
      {"result": [
       {"dn": "/O=GRID-FR/C=FR/O=CNRS/OU=IPNL/CN=Lucas Torterotot", "login": null, "method": "X509Proxy", "roles": {}, "name": null}
      ]}
      
    Parsed username: null
Note: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.
DEBUG 2018-06-13 13:24:24,743: 	 Executing command: 'checkusername'
DEBUG 2018-06-13 13:24:24,743: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:24:24,752: 	 Checking credentials
DEBUG 2018-06-13 13:24:24,753: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:24:24,753: 	 Getting proxy life time left
DEBUG 2018-06-13 13:24:25,658: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604425

 error: 
 retcode : 0
DEBUG 2018-06-13 13:24:26,472: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604424

 error: 
 retcode : 0
DEBUG 2018-06-13 13:24:26,472: 	 Proxy valid for 167:53:45 hours
DEBUG 2018-06-13 13:24:26,588: 	 Executing : 
 command : openssl x509 -in ~/.globus/usercert.pem -subject -noout
 output : subject= /O=GRID-FR/C=FR/O=CNRS/OU=IPNL/CN=Lucas Torterotot

 error: 
 retcode : 0
DEBUG 2018-06-13 13:24:26,588: 	 Checking credentials
DEBUG 2018-06-13 13:24:26,589: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:24:26,589: 	 Getting proxy life time left
DEBUG 2018-06-13 13:24:27,398: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604423

 error: 
 retcode : 0
DEBUG 2018-06-13 13:24:28,318: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604422

 error: 
 retcode : 0
DEBUG 2018-06-13 13:24:28,318: 	 Proxy valid for 167:53:43 hours
DEBUG 2018-06-13 13:24:28,318: 	 Command use: checkusername
DEBUG 2018-06-13 13:24:28,318: 	 Options use: []
DEBUG 2018-06-13 13:24:28,318: 	 Instance is None
DEBUG 2018-06-13 13:24:28,318: 	 Server base url is None
INFO 2018-06-13 13:24:28,318: 	 Retrieving DN from proxy...
INFO 2018-06-13 13:24:30,220: 	 DN is: /O=GRID-FR/C=FR/O=CNRS/OU=IPNL/CN=Lucas Torterotot
INFO 2018-06-13 13:24:30,220: 	 Retrieving username from SiteDB...
INFO 2018-06-13 13:24:33,625: 	 Username is: ltortero
DEBUG 2018-06-13 13:45:11,491: 	 Executing command: 'checkwrite'
DEBUG 2018-06-13 13:45:11,491: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 13:45:11,492: 	 Error: Please specify the site where to check the write permissions. Use the --site option.
ERROR 2018-06-13 13:45:11,492: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/checkwrite.py", line 22, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/checkwrite.py", line 262, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please specify the site where to check the write permissions. Use the --site option.
DEBUG 2018-06-13 13:57:52,857: 	 Executing command: 'submit'
DEBUG 2018-06-13 13:57:52,857: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
DEBUG 2018-06-13 13:57:52,865: 	 Checking credentials
DEBUG 2018-06-13 13:57:52,866: 	 Found proxy file /tmp/x509up_u113210
DEBUG 2018-06-13 13:57:52,866: 	 Getting proxy life time left
DEBUG 2018-06-13 13:57:54,274: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -timeleft
 output : 604788

 error: 
 retcode : 0
DEBUG 2018-06-13 13:57:55,186: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u113210 -actimeleft
 output : 604787

 error: 
 retcode : 0
DEBUG 2018-06-13 13:57:55,186: 	 Proxy valid for 167:59:48 hours
INFO 2018-06-13 13:57:55,187: 	 Will use CRAB configuration file heppy_crab_config_env.py
DEBUG 2018-06-13 13:57:55,187: 	 Loading CRAB configuration file.
DEBUG 2018-06-13 13:57:55,190: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2018-06-13 13:57:55,190: 	 Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
ERROR 2018-06-13 13:57:55,190: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z' already exists 
Please change the requestName in the config file
DEBUG 2018-06-13 14:24:42,518: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:42,519: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:42,525: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:42,525: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:45,244: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:45,244: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:45,245: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:45,245: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:47,962: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:47,962: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:47,962: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:47,963: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:50,655: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:50,656: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:50,656: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:50,656: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:53,590: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:53,590: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:53,591: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:53,591: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:56,237: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:56,237: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:56,238: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:56,238: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:24:58,924: 	 Executing command: 'status'
DEBUG 2018-06-13 14:24:58,924: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:24:58,925: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:24:58,925: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:01,622: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:01,623: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:01,624: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:01,624: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:04,255: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:04,256: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:04,256: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:04,256: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:06,863: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:06,863: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:06,864: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:06,864: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:09,543: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:09,543: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:09,544: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:09,544: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:12,274: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:12,274: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:12,274: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:12,275: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:14,889: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:14,890: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:14,890: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:14,890: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:17,549: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:17,549: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:17,550: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:17,550: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:20,217: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:20,218: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:20,219: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:20,219: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:22,959: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:22,960: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:22,960: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:22,960: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:25,612: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:25,612: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:25,613: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:25,613: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:28,361: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:28,361: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:28,362: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:28,362: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:31,463: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:31,463: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:31,464: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:31,464: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:34,168: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:34,169: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:34,169: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:34,169: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:36,805: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:36,805: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:36,805: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:36,806: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:41,498: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:41,498: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:41,499: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:41,499: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:44,812: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:44,812: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:44,813: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:44,813: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:47,391: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:47,391: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:47,392: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:47,392: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:25:49,994: 	 Executing command: 'status'
DEBUG 2018-06-13 14:25:49,994: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:25:49,994: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:25:49,994: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:49:53,993: 	 Executing command: 'status'
DEBUG 2018-06-13 14:49:53,994: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:49:53,996: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:49:53,996: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:49:56,707: 	 Executing command: 'status'
DEBUG 2018-06-13 14:49:56,707: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:49:56,708: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:49:56,708: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:49:59,344: 	 Executing command: 'status'
DEBUG 2018-06-13 14:49:59,344: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:49:59,345: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:49:59,345: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:03,151: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:03,151: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:03,494: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:03,495: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:06,198: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:06,198: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:06,199: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:06,199: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:08,903: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:08,903: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:08,904: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:08,904: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:11,614: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:11,614: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:11,615: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:11,615: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:14,262: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:14,262: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:14,263: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:14,263: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:16,895: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:16,895: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:17,036: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:17,036: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:20,648: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:20,648: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:21,048: 	 Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
ERROR 2018-06-13 14:50:21,048: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 575, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z is not a valid CRAB project directory.
DEBUG 2018-06-13 14:50:24,673: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:24,673: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:25,061: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:25,061: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:27,687: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:27,687: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:27,688: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:27,688: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:30,399: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:30,399: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:30,401: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:30,401: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:33,028: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:33,029: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:33,029: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:33,029: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:35,619: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:35,619: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:35,619: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:35,620: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:38,270: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:38,270: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:38,271: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:38,271: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:40,883: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:40,883: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:40,884: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:40,885: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:43,481: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:43,481: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:43,482: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:43,482: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:46,214: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:46,214: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:46,215: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:46,215: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:48,841: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:48,841: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:48,842: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:48,842: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:51,486: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:51,486: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:51,488: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:51,488: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:56,766: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:56,767: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:56,767: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:56,767: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:50:59,353: 	 Executing command: 'status'
DEBUG 2018-06-13 14:50:59,353: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:50:59,353: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:50:59,354: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:01,947: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:01,947: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:01,948: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:01,948: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:04,474: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:04,474: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:04,475: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:04,475: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:07,130: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:07,131: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:07,131: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:07,131: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:09,836: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:09,837: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:09,837: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:09,837: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:12,421: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:12,421: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:12,421: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:12,421: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:15,117: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:15,118: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:15,119: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:15,119: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:17,726: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:17,726: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:17,726: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:17,726: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:20,385: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:20,385: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:20,386: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:20,386: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:22,985: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:22,985: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:22,986: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:22,986: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:25,577: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:25,577: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:25,578: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:25,578: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:28,196: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:28,196: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:28,197: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:28,197: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:30,784: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:30,784: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:30,785: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:30,785: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:33,433: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:33,433: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:33,434: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:33,434: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:36,090: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:36,090: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:36,091: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:36,091: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:38,710: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:38,710: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:38,711: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:38,711: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:41,298: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:41,298: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:41,298: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:41,299: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:43,907: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:43,907: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:43,908: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:43,908: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:46,547: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:46,547: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:46,548: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:46,548: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:49,139: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:49,139: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:49,140: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:49,140: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:51,814: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:51,815: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:51,815: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:51,815: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:56,924: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:56,924: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:56,924: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:56,924: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:51:59,516: 	 Executing command: 'status'
DEBUG 2018-06-13 14:51:59,516: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:51:59,517: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:51:59,517: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:02,132: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:02,132: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:02,133: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:02,133: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:04,741: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:04,742: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:04,742: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:04,742: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:07,327: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:07,327: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:07,328: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:07,328: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:09,950: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:09,950: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:09,951: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:09,951: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:12,547: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:12,547: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:12,547: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:12,547: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:15,120: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:15,120: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:15,120: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:15,121: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:17,748: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:17,748: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:17,749: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:17,749: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:20,354: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:20,354: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:20,355: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:20,355: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:22,979: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:22,979: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:22,980: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:22,980: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:25,647: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:25,647: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:25,648: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:25,648: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:28,288: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:28,289: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:28,289: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:28,289: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:30,910: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:30,911: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:30,911: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:30,911: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:33,483: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:33,483: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:33,484: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:33,484: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:36,110: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:36,110: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:36,111: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:36,111: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:38,700: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:38,700: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:38,701: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:38,701: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:41,313: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:41,313: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:41,314: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:41,314: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
DEBUG 2018-06-13 14:52:43,877: 	 Executing command: 'status'
DEBUG 2018-06-13 14:52:43,877: 	 Found CRAB cache file /afs/cern.ch/user/l/ltortero/.crab3
ERROR 2018-06-13 14:52:43,878: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
ERROR 2018-06-13 14:52:43,878: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/l/ltortero/CMSSW/CMSSW_8_0_28_patch1/src/CMGTools/H2TauTau/cfgPython/crab/crab_test_component_myHeppyCrabProdDummy/crab_test_component_myCMGTools-from-CMSSW_X_Y_Z
